services:
  gobot:
    build: .
    container_name: gobot
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    volumes:
      - gobot_repo:/opt/gobot
      - ${HOME}/configs/gobot/config.ini:/config/config.ini:ro
      - ${HOME}/configs/gobot/battle_manager_state.json:/config/battle_manager_state.json:rw

volumes:
  gobot_repo:
